# Generated by Django 6.0.1 on 2026-01-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Título descriptivo de la plantilla.', max_length=255)),
                ('segmento', models.CharField(help_text="Categoría principal, ej: 'Visas', 'Residencias'.", max_length=100)),
                ('tipo_especifico', models.CharField(help_text="Subcategoría, ej: 'Residencia por Inversión'.", max_length=150)),
                ('archivo_base', models.FileField(help_text='Archivo PDF de la plantilla.', upload_to='plantillas_maestras/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la plantilla está disponible para su uso.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(help_text='Administrador que subió la plantilla.', limit_choices_to={'rol': 'ADMINISTRADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'db_table': 'tramites_plantilladocumento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
