# Generated by Django 6.0.1 on 2026-01-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_plantilladocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(help_text="Nombre que verá el usuario (ej: 'Nombre Completo').", max_length=100)),
                ('nombre_tecnico', models.SlugField(help_text="Nombre interno sin espacios (ej: 'nombre_completo').", max_length=100)),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto Corto'), ('textarea', 'Texto Largo'), ('email', 'Correo Electrónico'), ('date', 'Fecha'), ('number', 'Número'), ('checkbox', 'Casilla de Verificación')], max_length=20)),
                ('es_requerido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en el que aparecerá el campo en el formulario.')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='tramites.plantilladocumento')),
            ],
            options={
                'db_table': 'tramites_campoplantilla',
                'ordering': ['orden'],
                'unique_together': {('plantilla', 'nombre_tecnico')},
            },
        ),
    ]
