# Generated by Django 6.0.1 on 2026-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_campoplantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
