# Generated by Django 6.0.1 on 2026-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramite',
            options={'permissions': [('can_modify_own_tramite', 'Puede modificar sus propios trámites')]},
        ),
        migrations.AddField(
            model_name='tramite',
            name='datos_formulario',
            field=models.JSONField(blank=True, default=dict, help_text='Datos dinámicos del formulario del trámite'),
        ),
        migrations.AlterModelTable(
            name='tramite',
            table='tramites_tramite',
        ),
    ]
