# Generated by Django 6.0.1 on 2026-01-26 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_alter_tramite_options_tramite_datos_formulario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramite',
            options={'permissions': [('can_modify_own_tramite', 'Puede modificar sus propios trámites'), ('can_approve_tramite', 'Puede aprobar trámites')]},
        ),
        migrations.AddField(
            model_name='tramite',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, help_text='Empleado asignado automáticamente para revisar el trámite', limit_choices_to={'rol': 'EMPLEADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado aprobó el trámite', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado rechazó el trámite', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón del rechazo del trámite', null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('RETRASADO', 'Retrasado')], default='PENDIENTE', max_length=20),
        ),
    ]
