# Generated by Django 6.0.1 on 2026-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_alter_tramite_options_tramite_empleado_asignado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campoplantilla',
            options={'ordering': ['seccion', 'orden']},
        ),
        migrations.AddField(
            model_name='campoplantilla',
            name='seccion',
            field=models.CharField(default='Datos Personales', help_text='Sección del formulario a la que pertenece el campo.', max_length=100),
        ),
    ]
