# Generated by Django 6.0.1 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0009_historialcambios_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_empleado_id', models.IntegerField(blank=True, help_text='ID del último empleado asignado', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Última Asignación',
                'verbose_name_plural': 'Últimas Asignaciones',
            },
        ),
    ]
