# Generated by Django 6.0.1 manually

from django.db import migrations, models
import django.utils.timezone
import apps.tramites.models

class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0010_ultimaasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=apps.tramites.models.documento_upload_to),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
