# Generated by Django 6.0.1 on 2026-01-28 03:56

import apps.tramites.models
import apps.tramites.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0011_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=apps.tramites.storage.OverwriteStorage(), upload_to=apps.tramites.models.documento_upload_to),
        ),
    ]
